services:
  # Frontend Service
  - type: web
    name: portafolio-frontend
    env: node
    plan: free
    buildCommand: cd frontend && yarn install && yarn build
    startCommand: cd frontend && yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://portafolio-backend-iz92.onrender.com
    healthCheckPath: /
    autoDeploy: true

  # Backend Service
  - type: web
    name: portafolio-backend
    env: node
    plan: free
    buildCommand: cd backend && yarn install && npx nest build
    startCommand: cd backend && yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://portafolio-frontend-sehm.onrender.com
    healthCheckPath: /api
    autoDeploy: true 